### ISSUE TITLE
如何让正文和itemize body的字体一致

### ISSUE THREAD

**Issue by zyh1999** [HGGshiwo/BeamerthemeClassical#1]
具体来说
\begin{frame}
	xxxx
\begin{itemize}

    \item ppp
\end{itemize}
\end{frame}  
其中的xxxx 和 ppp的字体会不一致，应该如何修改

**Comment by zyh1999** [comment]
我在overleaf上用的

**Comment by HGGshiwo** [comment]
已修改，在sty文件中加入\AtBeginDocument{\rmfamily\yahei}即可。
